import { NgModule } from '@angular/core';

import { DecimalPipe } from '@angular/common';
import { AppAvailability } from '@ionic-native/app-availability/ngx';
import { InAppBrowser } from '@ionic-native/in-app-browser/ngx';
import {
  AddressBookProvider,
  AddressProvider,
  AndroidFingerprintAuth,
  Api,
  AppIdentityProvider,
  AppProvider,
  BackupProvider,
  Clipboard,
  ConfigProvider,
  DerivationPathHelperProvider,
  Device,
  EmailNotificationsProvider,
  ErrorProvider,
  ExternalLinkProvider,
  FeedbackProvider,
  FeeProvider,
  File,
  FilterProvider,
  IncomingDataProvider,
  LanguageProvider,
  Logger,
  NodeWebkitProvider,
  OnGoingProcessProvider,
  PayproProvider,
  PersistenceProvider,
  PlatformProvider,
  PopupProvider,
  ProfileProvider,
  PushNotificationsProvider,
  QRScanner,
  RateProvider,
  ReleaseProvider,
  ReplaceParametersProvider,
  ScanProvider,
  ScreenOrientation,
  SocialSharing,
  SplashScreen,
  SpvNodeProvider,
  StatusBar,
  TimeProvider,
  Toast,
  TouchID,
  TouchIdProvider,
  TxConfirmNotificationProvider,
  TxFormatProvider,
  Utils,
  Vibration,
  WalletProvider
} from './index';

@NgModule({
  providers: [
    AddressProvider,
    AddressBookProvider,
    AndroidFingerprintAuth,
    AppAvailability,
    AppProvider,
    AppIdentityProvider,
    BackupProvider,
    SpvNodeProvider,
    Utils,
    ErrorProvider,
    ConfigProvider,

    Clipboard,
    DerivationPathHelperProvider,
    Device,
    ExternalLinkProvider,
    FeedbackProvider,
    FeeProvider,

    InAppBrowser,
    IncomingDataProvider,
    LanguageProvider,
    Logger,
    { provide: 'console', useValue: console },

    NodeWebkitProvider,
    OnGoingProcessProvider,
    PayproProvider,
    PlatformProvider,
    ProfileProvider,
    PopupProvider,
    QRScanner,
    PushNotificationsProvider,
    RateProvider,
    ReleaseProvider,
    ReplaceParametersProvider,
    Api,
    StatusBar,
    SplashScreen,
    ScanProvider,
    ScreenOrientation,
    SocialSharing,
    Toast,
    TouchID,
    Vibration,
    TimeProvider,
    TouchIdProvider,
    TxConfirmNotificationProvider,
    FilterProvider,
    TxFormatProvider,
    WalletProvider,
    EmailNotificationsProvider,
    DecimalPipe,
    PersistenceProvider,
    File
  ]
})
export class ProvidersModule { }
